version: "3.9"

networks:
  typecho:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./typecho:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - typecho

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - typecho

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./typecho:/var/www/html:delegated
    networks:
      - typecho
