version: "3.9"

networks:
  wordpress:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: wp
    entrypoint: ["wp", "--allow-root"]
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress
